nuxt/learn.nuxt.com

composables/webContainer.ts
Trigger the `useWebContainer` multiple times before it first finish booting, it will call `WebContainer.boot()` multiple times and may break https://webcontainers.io/guides/quickstart#_1-create-a-webcontainer-instance
See the following simple code snippets
```js
function sleep(t = 1000) {
return new Promise(res => {
console.log('Sleep', t);
setTimeout(() => res(1), t);
});
}
let ins;
async function useInstance() {
if (!ins) ins = await sleep();
return ins;
}
useInstance();
useInstance();
useInstance();
// Log:
// Sleep 1000
// Sleep 1000
// Sleep 1000
// Not:
// Sleep 1000
```
=> fix: concurrent boot webcontainer

components/ColorSchemeToggle.vue, components/TheNav.vue, pages/index.vue
- Use `colorMode.preference` as `colorMode.value` is meant to be read-only. https://color-mode.nuxtjs.org/#usage
- Use a `<select>` instead of a button to add `system` option
Edit: I moved the logic into a toggle component and just use the original `colorMode.value`.
=> fix(color-mode): use color.preference & use select

components/ColorSchemeToggle.vue
The icon's orientation in colorMode has been reversed.
=> chore: invert icons

components/ThePlayground.client.vue
After my testing, I found that the Nuxt server undergoes several instances of unexpected reloading after the dev server starts. This causes `entry.js` to respond with HTML. I consider this a temporary solution and believe there should be a more elegant approach.
=> fix: prevent unexpected reloading to fix `entry.js` response html

components/ThePlayground.client.vue
If `{ exhaustive: true }` is not set in `import.meta.glob`, files starting with `.*` are not included by default, so I manually added `.npmrc`.
=> fix: including `.npmrc` for the basic template

components/PanelTerminal.vue, pages/[...slug].vue
- xterm `line-height` cannot be less than 1
https://github.com/xtermjs/xterm.js/blob/fb2c39cb5748e071e0a1ed49824590aafd45e65e/src/common/services/OptionsService.ts#L165-L170
- init right pane size mistake when left size is 100
https://github.com/nuxt/learn.nuxt.com/assets/54026110/4683745a-4ff2-45be-9664-7bd321abbc64
=> fix: init pane size mistake when left pane size 100

components/PanelDocs.vue
=> fix: remove content doc max width

composables/files-ignore.ts
Aha, I don't think this PR is worth mentioning. I hope I didn't do the wrong thing, make the wrong changes. 
Last night, I saw your live stream and thought about downloading it. 
I clicked on the download and found that there was a node_modules folder inside. 
It looked a little strange. So quickly put up a PR.
You might have fixed it, or it might be designed to contain node_modules, I do not understand your design intent, if good intentions do bad things, please do not be angry.
=> fix: add node_modules to INGORE_FILES

components/MainPlayground.vue, components/PanelPreview.vue, components/PanelTerminalClient.client.vue, stores/playground.ts
Hello, Antfu! I've made fresh attempts and coded a new interactivity shell!!!
And now, it work! first time auto-start, then user can able to interpret the Nuxt process with Ctrl+C!
And it can be relaunched using 'pnpm run dev'!!
this is first time auto-start:
then 'pnpm run dev' to start!:
=> feat: add interactivity shell after user terminiate Nuxt server

stores/playground.ts
Hello! antfu!
I just spotted a small snag: if someone hits Control + C while installing dependencies, maybe we should let them keep typing commands in the terminal to finish the install and get things running?
This 'throw' stops the program, so 'launchInteractiveProcess' doesn't run, and the terminal can't take input.
=> fix: enable command continuation post-install interruption.

templates/basic/package.json
For using Corepack to read `packageManager` config of `package.json`, we must specific a semver version to prevent following error:
```
Usage Error: Invalid package manager specification in package.json; expected a semver version
```
FYI, after my testing, web container will not read `packageManager` by default and it always use a default version (8.10.5 currently). Therefore the purpose of setting the `packageManager` for now is for the exported zip and development usage.
=> fix(template): use semver version of `packageManager`

templates/basic/.layer-playground/nuxt.config.ts
There are 2 problems from the original `./.layer-playground/**` config.
1. The `tsconfig` does not allow a file to end with `**`. The error message is:
2. When executing Nuxt in the `basic` folder, it generates a build folder in `basic/.nuxt` which includes `tsconfig`. Therefore, the relative path of `./.layer-playground` in that `tsconfig` would point to `basic/.nuxt/.layer-playground` instead of the correct `basic/.layer-playground`.
Thus, the correct `include` should be  `../.layer-playground/**/*`.
=> fix: include `.layer-playground` in template correctly

components/PanelEditorMonaco.client.vue
Hello! Antfu! I think when users hit Ctrl/Cmd + S in the Monaco Editor, we'll skip saving the page?
=> feat: Disable saving with Ctrl/Cmd + S in Monaco Editor.

components/PanelEditorMonaco.client.vue
Hello! Antfu!Tooltip gets cut off a bit when hovering over variables at the top or close to the edge. Should we fix this?
Before:
After:
=> fix: Monaco Editor tooltip obscuring API descriptions.

components/PanelTerminalClient.client.vue
I notice that everytime I toggle the terminal the scroll positioin will change a little bit.
I find a workaround.
=> fix: persist scroll position of terminal

components/PanelEditor.vue, components/TheNav.vue, composables/download.ts, composables/files-ignore.ts, content/2.concepts/2.app-vue/.template/index.ts, content/2.concepts/3.routing/.template/index.ts, stores/guide.ts, types/guides.ts
The current implementation uses a static [INGORE_FILES](https://github.com/nuxt/learn.nuxt.com/blob/420175560fc01f7ce5e8080eaa989dfe851987c5/composables/files-ignore.ts#L1).
Commit adds a `ignoredFiles` property to GuideMeta which dynamically computes the ignore file list when the guide is changed/mounted.
=> feat: allow each guide to configure file filter

components/ContentNavItem.vue
sorry I forgot to open an issue again first, but I think this is a simple PR.
this PR adds support to update content-nav-item component to dynamically open details based on route path. (for example after a refresh). also shows the active item by adding primary color to it.
=> feat: dynamic navItem opening based on route path

components/PanelDocs.vue, components/TheNav.vue, nuxt.config.ts
Added in `nuxt.config.ts` a new public env for the repo URL
=> feat: use runtime constant for repository URL

components/PanelPreview.vue
issue: #178 
the button was supposed to be shown but it never did, i don't know what was the purpose of checking `preview.url` and guide.features.navigation` but doing so made the refresh button never show.
=> fix: preview refresh button is now shown

content/2.concepts/4.auto-imports/.template/files/app.vue, content/2.concepts/4.auto-imports/.template/files/components/Counter.vue, content/2.concepts/4.auto-imports/.template/files/composables/counter.ts, content/2.concepts/4.auto-imports/.template/files/utils/double.ts, content/2.concepts/4.auto-imports/.template/index.ts, content/2.concepts/4.auto-imports/.template/solutions/app.vue, content/2.concepts/4.auto-imports/.template/solutions/components/Counter.vue, content/2.concepts/4.auto-imports/.template/solutions/composables/counter.ts, content/2.concepts/4.auto-imports/.template/solutions/utils/double.ts, content/2.concepts/4.auto-imports/index.md, content/2.concepts/5.middleware/.template/files/app.vue, content/2.concepts/5.middleware/.template/files/middleware/hello-foo.ts, content/2.concepts/5.middleware/.template/files/middleware/my-middleware.global.ts, content/2.concepts/5.middleware/.template/files/pages/foo.vue, content/2.concepts/5.middleware/.template/files/pages/index.vue, content/2.concepts/5.middleware/.template/index.ts, content/2.concepts/5.middleware/.template/solutions/app.vue, content/2.concepts/5.middleware/.template/solutions/middleware/my-middleware.global.ts, content/2.concepts/5.middleware/.template/solutions/pages/foo.vue, content/2.concepts/5.middleware/.template/solutions/pages/index.vue, content/2.concepts/5.middleware/index.md
Translate content form [Japanese](https://github.com/vuejs-jp/learn.nuxt.com) to English
| Title            | Status |
| ---------------- | ------ |
| Auto Imports     | OK     |
| Middleware       | OK   |
| Layout           | TODO   |
| Rendering Modes  | TODO   |
| State Management | TODO   |
| Data Fetching    | TODO   |
=> docs: translate content form Japanese to English

components/PanelDocs.vue
(~Didn't test the attribute class works -- but~ preview shows this part is working; see before/after with `overflow-y:auto` below)
=> fix: PanelDocs overflows container

content/ja/0.index.md
This pull request includes minor updates to the Japanese translation of the Nuxt tutorial to improve consistency in terminology. The changes involve replacing the word "概念" with "コンセプト" to ensure uniformity throughout the document.
Key changes:
* [`content/ja/0.index.md`](diffhunk://#diff-98a481b2459667fc96cdc894868e1c063ea73762ce036ccc35189f55698f5618L12-R12): Replaced "概念" with "コンセプト" in multiple instances to maintain consistency in terminology. [[1]](diffhunk://#diff-98a481b2459667fc96cdc894868e1c063ea73762ce036ccc35189f55698f5618L12-R12) [[2]](diffhunk://#diff-98a481b2459667fc96cdc894868e1c063ea73762ce036ccc35189f55698f5618L22-R33)
=> fix: correct terminology from "概念" to "コンセプト" in Japanese content

components/PanelEditor.vue, components/PanelPreview.vue, components/TheNav.vue, eslint.config.js, i18n/locales/en.yaml, i18n/locales/ja.yaml, package.json, pnpm-lock.yaml, pnpm-workspace.yaml
Hi dear @antfu,
I believe we recently added i18n support in #217, and there's actually an amazing linter specifically for that purpose.
https://github.com/intlify/eslint-plugin-vue-i18n
This linter can catch raw text in templates as well as missing message keys.  
~~I went ahead and tried introducing it, and while it caught some raw text issues, what do you think about going ahead and fixing those?~~
~~If so, I’m happy to help with the work — but if you’d prefer to cover this again on a livestream, then consider this just a suggestion and I’ll leave it to you!~~
=> chore: introduce eslint-plugin-vue-i18n

components/PanelDocs.vue
[Issue#226](https://github.com/nuxt/learn.nuxt.com/issues/226)
When generating the edit URL for content files, the `ja/` segment was being appended twice, resulting in paths like `ja/ja/...`. This fix ensures the path is generated correctly with only a single `ja/`.
=> fix: remove duplicated locale segment in source URL

content/en/1.vue/2.reactivity/index.md
In the code editor it is used the `doubled` computed property, but on the content side bar is used `double`. I changed it to reflect the name used in the editor to avoid confusion.
=> fix: typo in computed property name
