nuxt/learn.nuxt.com

- composables/webContainer.ts
- package.json
fix lint and case police the `webContainer` 👮‍♀️
> chore: lint fix

- templates/basic/tsconfig.json
Referenced tsconfig settings composite
https://github.com/nuxt/learn.nuxt.com/blob/151a627bb8d1dce484fba413f0f244bf3b9672e1/tsconfig.json#L4-L8
> chore: enabled templates tsconfig `composite`

- components/ThePlayground.client.vue
- composables/playground.ts
- templates/basic/app.vue
- templates/basic/pages/foo.vue
- templates/basic/pages/index.vue
https://github.com/nuxt/learn.nuxt.com/assets/44749100/c4ee3b2b-195c-433e-8241-e784321c4070
> feat: preview url path navigation

- templates/basic/pnpm-lock.yaml
This PR just updates the pnpm lock file in the basic template (`lockfileVersion: '6.1'`)
> chore: rebuild basic template lock file

- stores/playground.ts
> fix: revert `previewLocation` to `ref` type

- components/MainPlayground.vue
fix the preview pane size, solved #30
> fix: preview pane size

- components/ColorSchemeToggle.vue
> fix: save color mode after toggle

- components/PanelEditor.vue
> fix: remove textarea resize button

- nuxt.config.ts
Basically it's the same exact issue as the nuxt devtools is facing, COOP/COEP headers
Before the fix
After the fix
> fix: monaco thorwing unexpected error

- components/PanelEditor.vue
Adding debounce to the editor input just to close the TODO.
> chore: add debounce to editor input

- content/0.index.md
- content/1.vue/1.index.md
- content/1.vue/2.reactivity/index.md
- content/1.vue/5.summary/index.md
- content/2.concepts/1.index.md
- content/2.concepts/2.app-vue/index.md
This PR aims to fix some typos and grammar improvements.
> docs: typos & grammar improvments

- content/2.concepts/4.auto-imports/index.md
I am very much looking forward to the release of this repository!
I found a very small typo.
> docs: fix typo

- components/PanelTerminalClient.client.vue
this PR adds automatic scrolling to the bottom of the terminal when new text is written to ensure the latest output is always visible.
> feat: add scroll to bottom functionality to PanelTerminalClient

- content/2.concepts/6.server-side-rendering/index.md
- content/2.concepts/7.state-manegement/index.md
- content/2.concepts/8.data-fetching/index.md
- content/2.concepts/9.error-handling/index.md
I added some concepts ;D
If there are any tutorials that are necessary/unnecessary, please leave a comment on the PR. 😄 
---
I'm a bit concerned that `5.components` seems to exist in both `1.vue` and `2.concepts`. 
Is this a mistake? (Or does it explain something different?)
> docs: add some nuxt concepts

- components/TheNav.vue
> refactor: unified repo url with a const

- content/1.vue/1.index.md
> chore: spacing

- .github/workflows/autofix.yml
- .github/workflows/ci.yml
> chore(deps): update pnpm/action-setup action to v4

- components/TheNav.vue
Fixes an extremely minor typo/incorrect term for WIP
> refactor: use correct term for WIP

- content/2.concepts/2.app-vue/index.md
This PR translates the content of https://github.com/vuejs-jp/learn.nuxt.com/blob/main/content/2.concepts/2.app-vue/index.md into English. 😊
> add content of concepts/app-bue

- content/2.concepts/3.routing/.template/files/pages/foo.vue
- content/2.concepts/3.routing/.template/files/pages/index.vue
- content/2.concepts/3.routing/.template/files/pages/posts/[id].vue
- content/2.concepts/3.routing/index.md
This PR translates the content of https://github.com/vuejs-jp/learn.nuxt.com/blob/main/content/2.concepts/3.routing/index.md into English.
> add content of `concepts/routing`

- .github/workflows/nuxthub.yml
- components/ContentNavCard.vue
- components/ContentNavItem.vue
- components/MainPlayground.vue
- components/PanelDocs.vue
- content.config.ts
- eslint.config.js
- nuxt.config.ts
- package.json
- pnpm-lock.yaml
- stores/commands.ts
/cc @farnabaz could you scan the changes a bit and help me to verify if I migrated it correctly? Thank you!
> feat: migrate to Content v3
